// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhuvqanhpohruzmqfvxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodXZxYW5ocG9ocnV6bXFmdnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTg1MjgsImV4cCI6MjA2MjI5NDUyOH0.l3-w09gsfSWVY8sONI1zMFGkFqy3tupsbKMIp6sMc6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);